.gitignore, README.md
Corrected the setup and installation procedure.
=> changed readme

.gitignore, mysite/settings.py, mysite/urls.py, requirements.txt
added the requirements.txt for latest updates ....
and use python manage.py migrate command to set the things up
after localhost go to loaclhost/sharenlearn_hidden_admin------to acces the original admin panel.
=> SECURING  Django admin , by honepot

myapp/templates/login_admin.html
Form validation for the admin login page has been done with the help of bootstrap. Hope you will like it. If there still any issue please let me know.....:)
=> Form validation admin login page

.gitignore, mysite/settings.py, mysite/urls.py, requirements.txt
Reverts chiraag-kakar/sharenlearn#25
=> Revert "SECURING  Django admin , by honepot"

myapp/static/css/mystyle.css, myapp/templates/signup.html
=> improve UI

.gitignore, myapp/models.py
I have fixed the bug described in the issue no #15 . By accepting this pull request
- admin can save the notes objects.
- here is the image
=> Fixed #15 - no field name "signup"

mysite/settings.py, mysite/urls.py, requirements.txt
added features ,  updated requirements.txt to avoid conflicts
=> Secureing Django admin, with honeypot 

README.md
Reverts chiraag-kakar/sharenlearn#33
=> Revert "improving read me , to avoid conflict"

myapp/templates/admin_nav.html
Reverts chiraag-kakar/sharenlearn#37
=> Revert "Update admin navbar"

README.md, mysite/urls.py
previously 
honeypot was set in  /secret_admin which should be in /admin so i have fixed it  and the previously it was also working fine
=> Fix bug in /admin and /secret_admin

myapp/static/css/mystyle.css, myapp/templates/about.html, myapp/templates/accepted_notes.html, myapp/templates/admin_home.html, myapp/templates/admin_nav.html, myapp/templates/all_notes.html, myapp/templates/changepassword.html, myapp/templates/contact.html, myapp/templates/edit_profile.html, myapp/templates/footer.html, myapp/templates/index.html, myapp/templates/login.html, myapp/templates/login_admin.html, myapp/templates/navigation.html, myapp/templates/pending_notes.html, myapp/templates/signup.html, myapp/templates/upload_notes.html, myapp/templates/usernavigation.html, myapp/templates/view_usernotes.html, myapp/templates/view_users.html, myapp/templates/viewall_usernotes.html, myapp/views.py, mysite/urls.py
1. Customized the Footer according to the given color scheme. 
2. Included Social Icons and an iframe of Google Maps. 
3. Footer Section extended to all required pages. 
4. Made the Footer responsive.
=> Issue #5 - Added Footer Section

myapp/templates/navigation.html
- Admin now will be able to view admin specific nav links on the nav bar. 
- other normal users will have normal options
- For admins , the nav bar is shown below - 
- For other users, the nav bar will be normal
=> Solved #41 - Admin can see the admin specific options on home page

myapp/templates/about.html
Added parallax scroll effect
Added zoom in and out feature in image while scrolling
=> Update the about page

myapp/templates/about.html
Fixed Issue #51 
About page rendering was blocked due to an error in templating code.
=> Fixed Issue #51

myapp/templates/accepted_notes.html, myapp/templates/all_notes.html, myapp/templates/assign_status.html, myapp/templates/changepassword.html, myapp/templates/login.html, myapp/templates/login_admin.html, myapp/templates/pending_notes.html, myapp/templates/rejected_notes.html, myapp/templates/signup.html, myapp/templates/upload_notes.html, myapp/templates/view_usernotes.html, myapp/templates/view_users.html, myapp/templates/viewall_usernotes.html
- deprecated ifequal tag removed. 
- "if" tag is used instead.
=> Issue #16 - removed deprecated ifequal tag from templates

myapp/static/css/mystyle.css, myapp/templates/about.html
Debugged errors in mystyle.css and about.html.
=> Issue #53 Improper functionality of about page

myapp/templates/accepted_notes.html, myapp/templates/all_notes.html, myapp/templates/assign_status.html, myapp/templates/changepassword.html, myapp/templates/login.html, myapp/templates/login_admin.html, myapp/templates/pending_notes.html, myapp/templates/rejected_notes.html, myapp/templates/signup.html, myapp/templates/upload_notes.html, myapp/templates/view_usernotes.html, myapp/templates/view_users.html, myapp/templates/viewall_usernotes.html
- changed all if tags back to ifequal tags.
Hope that solves the issue, @chiraag-kakar ! Kindly reach out to me if there are any other changes to be made. Thanks.
=> Issue #56 solved (for signup and upload notes section)

myapp/templates/contact.html
Made all data fields required.
=> Minor enhancement in contact form

myapp/templates/login.html, myapp/views.py, mysite/settings.py, requirements.txt
- Added Recaptcha in the login form.
=> #73 Solved - Recaptcha checkbox in login form.

myapp/templates/signup.html
=> added required in input

myapp/views.py
#113 Solved 
[follw this for explanation](https://stackoverflow.com/questions/2990654/how-to-test-a-regex-password-in-python)
=> Signup password validation #113

myapp/templates/footer.html
Solves #55 
I have added a simple chatbot in footer.html
For now, It only works on buttons like login, admin-login
If you type Query it displays an about section and a contact button.
The buttons will take user to the required page on the website.
=> Dialogflow Chatbot

myapp/templates/image_carousel.html, myapp/templates/view_usernotes.html
- This PR Solves #79 
- Added a View Image Button which would show the uploaded image to the user
- It opens a new window
- It solves #79 in `http://localhost:8000/view_usernotes`
- Screenshot
=> Added View Image Button

myapp/templates/signup.html
This is a fix to the issue #165 where all the duplicate fields have been removed. Also, the footer has been fixed.
Resolves : #165
=> Signup page bug fix

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general_issue.md, .github/PULL_REQUEST_TEMPLATE.md
Closes #103
- Added PR and Issue templates in .`/github`
=> QA : Added Issue & PR templates

myapp/templates/navigation.html
##Desciption
Added preloader for the website. 
##Fixes
#129 
##Working Video
https://1drv.ms/v/s!AhQCqna6zNwBjiiNJwktCYepQU8w?e=yciURU
=> Added preloader

myapp/templates/viewall_usernotes.html
fixes issue #127
Made table in viewall_usernotes.html responsive as per issue #127
=> Made table in viewall_usernotes.html responsive as per issue #127

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/header.html
I've improved the UI of the Logout Alert Box.
Fixes: #249 
| Desktop | Mobile |
| --- | --- |
|![image](https://user-images.githubusercontent.com/58631762/118389804-4ddb0800-b649-11eb-8dd9-907cc1c8b3ee.png)|![image](https://user-images.githubusercontent.com/58631762/118389859-a6120a00-b649-11eb-9b08-b04ea75bab7a.png)|
Here's a gif,
=> Update Confirmation Logout Alert Box 

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/forgot_password.html, myapp/templates/login.html, myapp/views.py, mysite/urls.py
I've designed forgot password page where users can change their password with OTP Authentication.
Fixes: #253 
Remove this line and tell us how the code was tested.
Here's a gif,
=> Implement OTP Authentication for Forgot Password Page

myapp/static/js/scripts.js, myapp/templates/login.html, myapp/views.py, mysite/urls.py, requirements.txt
I've implemented email authentication to authenticate users.
Fixes: #252 
Here's a gif,
=> Email authentication

myapp/static/js/scripts.js, myapp/views.py
I've fixed the ReCaptcha issue that was discussed in #259 
Fixes: #259 
=> Fix captcha issue

myapp/static/js/scripts.js, myapp/views.py, requirements.txt
I've fixed the issue that was discussed in #261 and now users will get verification mail once they're successfully signed up to the site.
Fixes: #261
=> Fix issue in Email Authentication

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/edit_profile.html, myapp/templates/header.html, myapp/views.py, mysite/urls.py
I've implemented email authentication to change the user's password.
Fixes: #264 
Here's a gif,
=> Implement Email Authentication in Change Password Page

myapp/templates/header.html, myapp/views.py
I've fixed the issue that was discussed in #268.
Fixes: #268 
Here's a gif,
=> Fix Super User Profile Page Issue

myapp/templates/emails/mail_template.html, myapp/views.py
I've designed HTML Email Templates to send mail to the user's mail id.
Fixes: #270 
=> Design HTML email templates

myapp/static/css/styles.css, myapp/templates/footer1.html
Adding top-button
Fixes: #251 
=> Adding Top-button

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/contact.html, myapp/templates/footer1.html, myapp/templates/home.html, myapp/views.py
I've updated the contact form and fixed the issue that was discussed in #273 
Fixes: #273
Here's a gif,
=> Update contact form

myapp/templates/emails/mail_template.html, myapp/views.py
I've updated things that I discussed in issue #276 
* Updated views sending email after a successful password change.
* Designed HTML Email Templates for them, (shown in gif)
Fixes: #276 
Here's a gif,
=> Password Reset Code and Password Changed HTML Email Templates

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/home.html, myapp/views.py, mysite/urls.py
I've added OTP authentication in the contact form.
Fixes: #278 
Remove this line and tell us how the code was tested.
=> Implement OTP auth for contact form

myapp/templates/emails/contact_template.html, myapp/templates/emails/mail_template.html, myapp/views.py
I've added contact form HTML Email Templates
Fixes: #280 
=> Contact Form HTML Email Templates

myapp/static/css/styles.css, myapp/static/js/scripts.js, myapp/templates/admin_dashboard.html, myapp/templates/base.html, myapp/templates/header.html
* I've fixed UI issues that were discussed in #284 
* When a user clicks the form button, invalid fields were not being focused because of the sticky header. I've fixed that issue by adding a script.
* I've added an 'all' field in the dropdown (staff admin page), then the drop-down was not being closed once clicked the filter title again. I've fixed that too.
Fixes: #284
- [] Your submission doesn't break any existing feature.
=> Fix UI issues

myapp/static/js/scripts.js, myapp/templates/footer1.html
I've created a new chatbot using Dialogflow and added it to the footer of the site.
Fixes: #289 
Here's a gif,
=> Add Chatbot (Dialogflow) at the footer

README.md
=> README bug fixed

myapp/static/css/styles.css, myapp/templates/view_note.html, myapp/views.py
Users will get the delete button near the note if it is uploaded by him. Clicking the delete button will delete the particular note.
Fixes: #306 
Remove this line and tell us how the code was tested.
=> Delete note functionality
